Cleaning in progress

diff --git a/bin/cmd/down b/bin/cmd/down
--- a/bin/cmd/down
+++ b/bin/cmd/down
@@ -1,19 +1,47 @@
 #!/bin/bash
 
-# Check Docker Compose YML, this file is mandatory to up services
-if [[ ! -e docker-compose.yml ]]; then
-    echo "Missing docker-compose.yml"
-    exit
+CURRENT_PATH="${PWD}"
+CONTAINER=$1
+STATUS=0
+
+function _down {
+    SOURCE=$1
+    echo "[INFO] Down all services ${SOURCE} ?"
+    echo "Please type yes or no and Press [Enter]: "
+    read  OP
+
+    if [[ $OP == "yes" ]]; then
+        docker-compose stop
+        docker-compose down
+        docker system prune --force
+    fi
+}
+
+if [[ -e "${CURRENT_PATH}/docker-compose.yml" ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/"
+    STATUS=1
+    _down "projects"
 fi
 
-echo "[INFO] Down all services ?"
-echo "Please type yes or no and Press [Enter]: "
-read  OP
+if [[ -e "${CURRENT_PATH}/web/docker-compose.yml" && "${STATUS}" == 0 ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/web/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/web/"
+    STATUS=1
+    _down "web"
+fi
 
-if [[ $OP == "yes" ]]; then
-    docker-compose stop
-    docker-compose down
-    docker system prune --force
+if [[ ${STATUS} == 0 ]]; then
+    echo "Missing docker-compose.yml"
+    exit
 fi
 
 echo "Down Finished"
diff --git a/bin/cmd/exec b/bin/cmd/exec
--- a/bin/cmd/exec
+++ b/bin/cmd/exec
@@ -1,11 +1,33 @@
 #!/bin/bash
 
-if [[ ! -e docker-compose.yml ]]; then
-    echo "Missing ocker-compose.yml"
-    exit
+CURRENT_PATH="${PWD}"
+CONTAINER=$1
+STATUS=0
+
+if [[ -e "${CURRENT_PATH}/docker-compose.yml" ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/"
+    STATUS=1
 fi
 
-CONTAINER=$1
+if [[ -e "${CURRENT_PATH}/web/docker-compose.yml" && "${STATUS}" == 0 ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/web/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/web/"
+    STATUS=1
+fi
+
+if [[ ${STATUS} == 0 ]]; then
+    echo "Missing docker-compose.yml"
+    exit
+fi
 
 docker exec -it "${CONTAINER}" /bin/bash
 
diff --git a/bin/cmd/off b/bin/cmd/off
--- a/bin/cmd/off
+++ b/bin/cmd/off
@@ -1,22 +1,50 @@
 #!/bin/bash
 
-if [[ ! -e docker-compose.yml ]]; then
-    echo "Missing ocker-compose.yml"
+CURRENT_PATH="${PWD}"
+CONTAINER=$1
+STATUS=0
+
+function _off {
+    if [[ "${CONTAINER}" != "" ]]; then
+        echo "[INFO] Power off service ${CONTAINER} ?"
+        echo "Please type yes or no and Press [Enter]: "
+        read  OP
+    else
+        echo "[INFO] Power off all services ?"
+        echo "Please type yes or no and Press [Enter]: "
+        read  OP
+    fi
+
+    if [[ $OP == "yes" ]]; then
+        docker-compose stop "${CONTAINER}"
+    fi
+}
+
+if [[ -e "${CURRENT_PATH}/docker-compose.yml" ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/"
+    STATUS=1
+    _off
+fi
+
+if [[ -e "${CURRENT_PATH}/web/docker-compose.yml" && "${STATUS}" == 0 ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/web/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/web/"
+    STATUS=1
+    _off
+fi
+
+if [[ ${STATUS} == 0 ]]; then
+    echo "Missing docker-compose.yml"
     exit
-fi
-
-if [[ $1 != "" ]]; then
-    echo "[INFO] Power off service $1 ?"
-    echo "Please type yes or no and Press [Enter]: "
-    read  OP
-else
-    echo "[INFO] Power off all services ?"
-    echo "Please type yes or no and Press [Enter]: "
-    read  OP
-fi
-
-if [[ $OP == "yes" ]]; then
-    docker-compose stop $1
 fi
 
 echo "Off Finished"
diff --git a/bin/cmd/ps b/bin/cmd/ps
--- a/bin/cmd/ps
+++ b/bin/cmd/ps
@@ -1,23 +1,51 @@
 #!/bin/bash
 
-if [[ ! -e docker-compose.yml ]]; then
+CURRENT_PATH="${PWD}"
+CONTAINER=$1
+STATUS=0
+
+function _ps {
+    echo ""
+    echo "Docker"
+    echo "-------------------------------------------------------------------------"
+    docker ps
+
+    echo ""
+    echo ""
+    echo "*************************************************************************"
+
+    echo ""
+    echo "Docker Compose"
+    echo "-------------------------------------------------------------------------"
+    docker-compose ps
+}
+
+if [[ -e "${CURRENT_PATH}/docker-compose.yml" ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/"
+    STATUS=1
+    _ps
+fi
+
+if [[ -e "${CURRENT_PATH}/web/docker-compose.yml" && "${STATUS}" == 0 ]]; then
+    if ! egrep "${CONTAINER}" "${CURRENT_PATH}/web/docker-compose.yml" >> /dev/null 2>&1
+    then
+        echo "[ERROR] Missing container name [${CONAINER}], abort"
+        exit
+    fi
+    cd "${CURRENT_PATH}/web/"
+    STATUS=1
+    _ps
+fi
+
+if [[ ${STATUS} == 0 ]]; then
     echo "Missing docker-compose.yml"
     exit
 fi
-
-echo ""
-echo "Docker"
-echo "-------------------------------------------------------------------------"
-docker ps
-
-echo ""
-echo ""
-echo "*************************************************************************"
-
-echo ""
-echo "Docker Compose"
-echo "-------------------------------------------------------------------------"
-docker-compose ps
 
 echo "PS Finished"
 exit
diff --git a/bin/env/env_start b/bin/env/env_start
--- a/bin/env/env_start
+++ b/bin/env/env_start
@@ -1,25 +1,65 @@
 #!/bin/bash
 
+PROJECTS_UP=$1
 DATE_NOW=$(date +"%d%m%y%H%m%s")
-
 DOCKERIZED_WEB_PATH="${PWD}/web/"
 
-cd "${DOCKERIZED_WEB_PATH}"
-docker-compose start
+function _projects {
+    echo ""
+    echo "Dockerized will be up services by docker-compose, please wait"
+    echo ""
 
-#java -jar dockerized-web-api.jar
+    docker-compose start
 
-IP_POSSIBLE=$(ip addr | grep "inet" | grep "dynamic" | awk '{print $2}' | cut -f1 -d'/')
+    if [[ $? != 0 ]]; then
+        echo "[ERROR] Docker Compose found an error during web installation..."
+        return 500
+    fi
 
-if [[ ${IP_POSSIBLE} == "" ]]; then
-    IP_POSSIBLE="UNKNOWN"
+    exit
+}
+
+function _web {
+    cd "${DOCKERIZED_WEB_PATH}"
+
+    docker-compose start
+
+    if [[ $? != 0 ]]; then
+        echo "[ERROR] Docker Compose found an error during web installation..."
+        return 500
+    fi
+
+    #TODO: Subir serviço java do dockerized
+    #java -jar dockerized-web-api.jar
+
+    #-----------------------------------------------------------------------------------------------
+    #FINISHED
+    #-----------------------------------------------------------------------------------------------
+
+    IP_POSSIBLE_LOCAL_SERVER=$(ip addr | grep "inet" | grep "dynamic" | awk '{print $2}' | cut -f1 -d'/')
+    IP_POSSIBLE_SERVER=""
+    if [[ ${IP_POSSIBLE_LOCAL_SERVER} != "" ]]; then
+        IP_POSSIBLE_SERVER="http://${IP_POSSIBLE_LOCAL_SERVER}:31800"
+    fi
+
+    IP_POSSIBLE_REMOTE_ACCESS=$(who | grep "pts" | awk '{print $5}' | sed -e 's/[^0-9.]//g')
+    IP_POSSIBLE_REMOTE=""
+    if [[ ${IP_POSSIBLE_REMOTE_ACCESS} != "" ]]; then
+        IP_POSSIBLE_REMOTE="http://${IP_POSSIBLE_REMOTE_ACCESS}"
+    fi
+
+    echo "-----------------------------------------------------------------------------------------------"
+    echo "Dockerized Web say: Everything fine !"
+    echo "-----------------------------------------------------------------------------------------------"
+    echo "You can be accessed the configuration services in:"
+    echo "Local IP: http://localhost:31800, http://127.0.0.1:31800, ${IP_POSSIBLE_SERVER}"
+    echo "Remote IP: http://192.168.1.100:31800 (SAMPLE REMOTE IP), ${IP_POSSIBLE_REMOTE}"
+    echo "Local Service Name: http://dockerized_web:31800 (IF CONFIGURED ON SERVER/DNS)"
+    echo "-----------------------------------------------------------------------------------------------"
+}
+
+if [[ ${PROJECTS_UP} == "projects" ]]; then
+    _projects
+else
+    _web
 fi
-
-echo "-----------------------------------------------------------------------------------------------"
-echo "Dockerized Web is Up now !"
-echo "-----------------------------------------------------------------------------------------------"
-echo "You can be accessed the configuration services in:"
-echo "Local IP: http://localhost:31800, http://127.0.0.1:31800, http://${IP_POSSIBLE}:31800"
-echo "Remote IP: http://192.168.1.100:31800 (SAMPLE REMOTE IP)"
-echo "Local Service Name: http://dockerized_web:31800 (IF CONFIGURED)"
-echo "-----------------------------------------------------------------------------------------------"
diff --git a/dockerized b/dockerized
--- a/dockerized
+++ b/dockerized
@@ -48,6 +48,7 @@ COMMANDS=",--web,--install,--refresh,--start,--stop,--status,--restart,--exec,--
 COMMAND1="$1"
 COMMAND2="$2"
 JAVA_VERSION_EXPECTED="1.8.0"
+FILE_PROFILE="profile.txt"
 
 function help {
     echo -e "${BACK_BLACK_COLOR}"
@@ -208,6 +209,11 @@ function run_web {
     _prepare_settings
     _dockerized_web
 
+    if [[ $? == 500 ]]; then
+        echo -e "${RED_TEXT_COLOR}WEB failed...${COLOR_CLOSE}"
+        exit
+    fi
+
     _dockerized_allow -y
     sleep 2
 
@@ -268,8 +274,15 @@ function run_uninstall {
 
 source ./bin/colours
 
+#Properties File
+touch "${FILE_PROFILE}"
+sudo chmod 777 "${FILE_PROFILE}"
+sudo chown nobody:nogroup "${FILE_PROFILE}"
+
+echo "CURRENT_PATH=${PWD};" >> "${FILE_PROFILE}" 2>&1
+
 #-----------------------------------------------------------------------------------------------
-#CHECKIN
+#CHECKIN AND HELP [DONE]
 #-----------------------------------------------------------------------------------------------
 
 if [[ "${COMMAND1}" == "--help" ]];
@@ -280,7 +293,7 @@ fi
 run_checkin
 
 #-----------------------------------------------------------------------------------------------
-#WEB CONFIGURATIONS PROCESS
+#WEB CONFIGURATIONS PROCESS - [DONE]
 #-----------------------------------------------------------------------------------------------
 
 if [[ "${COMMAND1}" == "--web" ]];
@@ -315,7 +328,7 @@ then
 fi
 
 #-----------------------------------------------------------------------------------------------
-#INSTALL
+#INSTALL - [WAIT]
 #-----------------------------------------------------------------------------------------------
 
 if [[ "${COMMAND1}" == "--install" ]];
